### ISSUE TITLE
Move all Hapi plugins directly into this repository

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/api#28]
Since we will be shipping this whole application as one (plugins and all), should we move all the user interface plugins (repos named `plugin-*`) directly into this repository, so it reduces the dependency and development chain?

**Comment by tkyi** [comment]
Since every time we need to make a change to the schema or model we end up making changes to each plugin, it would make more sense to move all `plugin-` repositories into one 

Do we see any use cases where people might want to be tied to different versions of plugins- repositories?

**Comment by stjohnjohnson** [comment]
@tkyi i can only think of the case where you would want a V3 and V4 api. But even so, you can't install two of the same version of a npm module.
